### ISSUE TITLE
game crashes on load with mod generated from website (1.16.5)

### ISSUE THREAD

**Issue by Thumtacka** [glossnyx/disco#10]
[crash-2024-07-16_16.28.44-client.txt](https://github.com/user-attachments/files/16256767/crash-2024-07-16_16.28.44-client.txt)

Loading the game without any generated disc mods works fine, yet when I create one with the website, the game will fail to start. The only mods I have loaded are Fabric API, Fabric Language Kotlin, Disco, and the generated mod with 1 disc added. The file was in .ogg format, mono, all the specifications were met, but it still just _doesn't work,_ and I'm not sure why.

**Comment by Thumtacka** [comment]
upon closer inspection this is probably due to the website generating disc mods for latest version which uses objects for items instead of 1.16.5 which uses strings, so it ends up not working.
Would it be possible, then, to add compatibility for earlier versions to the website?

**Comment by Thumtacka** [comment]
alternatively this could be an issue with the mod itself? crash logs say "can't convert OBJECT to String" with the problem area being in Addons.kt at line 21?
Had a friend look at it and that seems to add up, though he doesn't have experience in Kotlin so we could be wrong
I know updating legacy versions aren't generally a priority for most, I just thought I'd ask.

**Comment by auxves** [comment]
I just backported `v2.0.8` to 1.16 👍🏼
