### ISSUE TITLE
game crash on launch from jar generated from webapp

### ISSUE THREAD

**Issue by jammque** [glossnyx/disco#12]
Linux
MC 1.20.1
QUILT 0.25.0
`Unable to read /.minecraft/mods/ghost.jar as a zip file: only DEFLATED entries can have EXT descriptor <mods>/ghost.jar`

it has been running fine before i put in my addon
idk what is causing it but i would prefer to continue using quilt, it was the base modpack i was working with and i dont wanna have to bother switching it to fabric in case it just doesnt start working as is when i do

**Comment by auxves** [comment]
The issue should now be fixed in the web app. You can either re-export your draft, or extract & recompress the jar with a command like `jar cvf ghost.jar .` within the extracted directory.
